/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AppRouteImport } from './routes/app'
import { Route as BancosRouteImport } from './routes/bancos'
import { Route as CartaoDeCreditoRouteImport } from './routes/cartao-de-credito'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CofrinhosRouteImport } from './routes/cofrinhos'
import { Route as ControleFinanceiroRouteImport } from './routes/controle-financeiro'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GastosFixosRouteImport } from './routes/gastos-fixos'
import { Route as GastosVariaveisRouteImport } from './routes/gastos-variaveis'
import { Route as ImersaoefpfjRouteImport } from './routes/imersaoefpfj'
import { Route as ImportarDadosRouteImport } from './routes/importar-dados'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NataliaRouteImport } from './routes/natalia'
import { Route as PassoAPassoRouteImport } from './routes/passo-a-passo'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RecebimentosRouteImport } from './routes/recebimentos'
import { Route as ReservaDeEmergenciaRouteImport } from './routes/reserva-de-emergencia'
import { Route as SegundoUsuarioRouteImport } from './routes/segundo-usuario'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as VeraGerenteRouteImport } from './routes/vera-gerente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BancosRoute = BancosRouteImport.update({
  id: '/bancos',
  path: '/bancos',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoDeCreditoRoute = CartaoDeCreditoRouteImport.update({
  id: '/cartao-de-credito',
  path: '/cartao-de-credito',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CofrinhosRoute = CofrinhosRouteImport.update({
  id: '/cofrinhos',
  path: '/cofrinhos',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleFinanceiroRoute = ControleFinanceiroRouteImport.update({
  id: '/controle-financeiro',
  path: '/controle-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosFixosRoute = GastosFixosRouteImport.update({
  id: '/gastos-fixos',
  path: '/gastos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosVariaveisRoute = GastosVariaveisRouteImport.update({
  id: '/gastos-variaveis',
  path: '/gastos-variaveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ImersaoefpfjRoute = ImersaoefpfjRouteImport.update({
  id: '/imersaoefpfj',
  path: '/imersaoefpfj',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarDadosRoute = ImportarDadosRouteImport.update({
  id: '/importar-dados',
  path: '/importar-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NataliaRoute = NataliaRouteImport.update({
  id: '/natalia',
  path: '/natalia',
  getParentRoute: () => rootRouteImport,
} as any)
const PassoAPassoRoute = PassoAPassoRouteImport.update({
  id: '/passo-a-passo',
  path: '/passo-a-passo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentosRoute = RecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaDeEmergenciaRoute = ReservaDeEmergenciaRouteImport.update({
  id: '/reserva-de-emergencia',
  path: '/reserva-de-emergencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SegundoUsuarioRoute = SegundoUsuarioRouteImport.update({
  id: '/segundo-usuario',
  path: '/segundo-usuario',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const VeraGerenteRoute = VeraGerenteRouteImport.update({
  id: '/vera-gerente',
  path: '/vera-gerente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/app': typeof AppRoute
  '/bancos': typeof BancosRoute
  '/cartao-de-credito': typeof CartaoDeCreditoRoute
  '/categorias': typeof CategoriasRoute
  '/cofrinhos': typeof CofrinhosRoute
  '/controle-financeiro': typeof ControleFinanceiroRoute
  '/dashboard': typeof DashboardRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/imersaoefpfj': typeof ImersaoefpfjRoute
  '/importar-dados': typeof ImportarDadosRoute
  '/investimentos': typeof InvestimentosRoute
  '/login': typeof LoginRoute
  '/natalia': typeof NataliaRoute
  '/passo-a-passo': typeof PassoAPassoRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recebimentos': typeof RecebimentosRoute
  '/reserva-de-emergencia': typeof ReservaDeEmergenciaRoute
  '/segundo-usuario': typeof SegundoUsuarioRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vera-gerente': typeof VeraGerenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/app': typeof AppRoute
  '/bancos': typeof BancosRoute
  '/cartao-de-credito': typeof CartaoDeCreditoRoute
  '/categorias': typeof CategoriasRoute
  '/cofrinhos': typeof CofrinhosRoute
  '/controle-financeiro': typeof ControleFinanceiroRoute
  '/dashboard': typeof DashboardRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/imersaoefpfj': typeof ImersaoefpfjRoute
  '/importar-dados': typeof ImportarDadosRoute
  '/investimentos': typeof InvestimentosRoute
  '/login': typeof LoginRoute
  '/natalia': typeof NataliaRoute
  '/passo-a-passo': typeof PassoAPassoRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recebimentos': typeof RecebimentosRoute
  '/reserva-de-emergencia': typeof ReservaDeEmergenciaRoute
  '/segundo-usuario': typeof SegundoUsuarioRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vera-gerente': typeof VeraGerenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajuda': typeof AjudaRoute
  '/app': typeof AppRoute
  '/bancos': typeof BancosRoute
  '/cartao-de-credito': typeof CartaoDeCreditoRoute
  '/categorias': typeof CategoriasRoute
  '/cofrinhos': typeof CofrinhosRoute
  '/controle-financeiro': typeof ControleFinanceiroRoute
  '/dashboard': typeof DashboardRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/gastos-variaveis': typeof GastosVariaveisRoute
  '/imersaoefpfj': typeof ImersaoefpfjRoute
  '/importar-dados': typeof ImportarDadosRoute
  '/investimentos': typeof InvestimentosRoute
  '/login': typeof LoginRoute
  '/natalia': typeof NataliaRoute
  '/passo-a-passo': typeof PassoAPassoRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/recebimentos': typeof RecebimentosRoute
  '/reserva-de-emergencia': typeof ReservaDeEmergenciaRoute
  '/segundo-usuario': typeof SegundoUsuarioRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vera-gerente': typeof VeraGerenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/app'
    | '/bancos'
    | '/cartao-de-credito'
    | '/categorias'
    | '/cofrinhos'
    | '/controle-financeiro'
    | '/dashboard'
    | '/gastos-fixos'
    | '/gastos-variaveis'
    | '/imersaoefpfj'
    | '/importar-dados'
    | '/investimentos'
    | '/login'
    | '/natalia'
    | '/passo-a-passo'
    | '/perfil'
    | '/politica-de-privacidade'
    | '/recebimentos'
    | '/reserva-de-emergencia'
    | '/segundo-usuario'
    | '/termos-de-uso'
    | '/vera-gerente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajuda'
    | '/app'
    | '/bancos'
    | '/cartao-de-credito'
    | '/categorias'
    | '/cofrinhos'
    | '/controle-financeiro'
    | '/dashboard'
    | '/gastos-fixos'
    | '/gastos-variaveis'
    | '/imersaoefpfj'
    | '/importar-dados'
    | '/investimentos'
    | '/login'
    | '/natalia'
    | '/passo-a-passo'
    | '/perfil'
    | '/politica-de-privacidade'
    | '/recebimentos'
    | '/reserva-de-emergencia'
    | '/segundo-usuario'
    | '/termos-de-uso'
    | '/vera-gerente'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajuda'
    | '/app'
    | '/bancos'
    | '/cartao-de-credito'
    | '/categorias'
    | '/cofrinhos'
    | '/controle-financeiro'
    | '/dashboard'
    | '/gastos-fixos'
    | '/gastos-variaveis'
    | '/imersaoefpfj'
    | '/importar-dados'
    | '/investimentos'
    | '/login'
    | '/natalia'
    | '/passo-a-passo'
    | '/perfil'
    | '/politica-de-privacidade'
    | '/recebimentos'
    | '/reserva-de-emergencia'
    | '/segundo-usuario'
    | '/termos-de-uso'
    | '/vera-gerente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjudaRoute: typeof AjudaRoute
  AppRoute: typeof AppRoute
  BancosRoute: typeof BancosRoute
  CartaoDeCreditoRoute: typeof CartaoDeCreditoRoute
  CategoriasRoute: typeof CategoriasRoute
  CofrinhosRoute: typeof CofrinhosRoute
  ControleFinanceiroRoute: typeof ControleFinanceiroRoute
  DashboardRoute: typeof DashboardRoute
  GastosFixosRoute: typeof GastosFixosRoute
  GastosVariaveisRoute: typeof GastosVariaveisRoute
  ImersaoefpfjRoute: typeof ImersaoefpfjRoute
  ImportarDadosRoute: typeof ImportarDadosRoute
  InvestimentosRoute: typeof InvestimentosRoute
  LoginRoute: typeof LoginRoute
  NataliaRoute: typeof NataliaRoute
  PassoAPassoRoute: typeof PassoAPassoRoute
  PerfilRoute: typeof PerfilRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RecebimentosRoute: typeof RecebimentosRoute
  ReservaDeEmergenciaRoute: typeof ReservaDeEmergenciaRoute
  SegundoUsuarioRoute: typeof SegundoUsuarioRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  VeraGerenteRoute: typeof VeraGerenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bancos': {
      id: '/bancos'
      path: '/bancos'
      fullPath: '/bancos'
      preLoaderRoute: typeof BancosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao-de-credito': {
      id: '/cartao-de-credito'
      path: '/cartao-de-credito'
      fullPath: '/cartao-de-credito'
      preLoaderRoute: typeof CartaoDeCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofrinhos': {
      id: '/cofrinhos'
      path: '/cofrinhos'
      fullPath: '/cofrinhos'
      preLoaderRoute: typeof CofrinhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle-financeiro': {
      id: '/controle-financeiro'
      path: '/controle-financeiro'
      fullPath: '/controle-financeiro'
      preLoaderRoute: typeof ControleFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-fixos': {
      id: '/gastos-fixos'
      path: '/gastos-fixos'
      fullPath: '/gastos-fixos'
      preLoaderRoute: typeof GastosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-variaveis': {
      id: '/gastos-variaveis'
      path: '/gastos-variaveis'
      fullPath: '/gastos-variaveis'
      preLoaderRoute: typeof GastosVariaveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imersaoefpfj': {
      id: '/imersaoefpfj'
      path: '/imersaoefpfj'
      fullPath: '/imersaoefpfj'
      preLoaderRoute: typeof ImersaoefpfjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-dados': {
      id: '/importar-dados'
      path: '/importar-dados'
      fullPath: '/importar-dados'
      preLoaderRoute: typeof ImportarDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natalia': {
      id: '/natalia'
      path: '/natalia'
      fullPath: '/natalia'
      preLoaderRoute: typeof NataliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passo-a-passo': {
      id: '/passo-a-passo'
      path: '/passo-a-passo'
      fullPath: '/passo-a-passo'
      preLoaderRoute: typeof PassoAPassoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimentos': {
      id: '/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof RecebimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva-de-emergencia': {
      id: '/reserva-de-emergencia'
      path: '/reserva-de-emergencia'
      fullPath: '/reserva-de-emergencia'
      preLoaderRoute: typeof ReservaDeEmergenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segundo-usuario': {
      id: '/segundo-usuario'
      path: '/segundo-usuario'
      fullPath: '/segundo-usuario'
      preLoaderRoute: typeof SegundoUsuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vera-gerente': {
      id: '/vera-gerente'
      path: '/vera-gerente'
      fullPath: '/vera-gerente'
      preLoaderRoute: typeof VeraGerenteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjudaRoute: AjudaRoute,
  AppRoute: AppRoute,
  BancosRoute: BancosRoute,
  CartaoDeCreditoRoute: CartaoDeCreditoRoute,
  CategoriasRoute: CategoriasRoute,
  CofrinhosRoute: CofrinhosRoute,
  ControleFinanceiroRoute: ControleFinanceiroRoute,
  DashboardRoute: DashboardRoute,
  GastosFixosRoute: GastosFixosRoute,
  GastosVariaveisRoute: GastosVariaveisRoute,
  ImersaoefpfjRoute: ImersaoefpfjRoute,
  ImportarDadosRoute: ImportarDadosRoute,
  InvestimentosRoute: InvestimentosRoute,
  LoginRoute: LoginRoute,
  NataliaRoute: NataliaRoute,
  PassoAPassoRoute: PassoAPassoRoute,
  PerfilRoute: PerfilRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RecebimentosRoute: RecebimentosRoute,
  ReservaDeEmergenciaRoute: ReservaDeEmergenciaRoute,
  SegundoUsuarioRoute: SegundoUsuarioRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  VeraGerenteRoute: VeraGerenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
