/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartaoDeCreditoRouteImport } from './routes/cartao-de-credito'
import { Route as ControleFinanceiroRouteImport } from './routes/controle-financeiro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoDeCreditoRoute = CartaoDeCreditoRouteImport.update({
  id: '/cartao-de-credito',
  path: '/cartao-de-credito',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleFinanceiroRoute = ControleFinanceiroRouteImport.update({
  id: '/controle-financeiro',
  path: '/controle-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartao-de-credito': typeof CartaoDeCreditoRoute
  '/controle-financeiro': typeof ControleFinanceiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartao-de-credito': typeof CartaoDeCreditoRoute
  '/controle-financeiro': typeof ControleFinanceiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartao-de-credito': typeof CartaoDeCreditoRoute
  '/controle-financeiro': typeof ControleFinanceiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cartao-de-credito' | '/controle-financeiro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cartao-de-credito' | '/controle-financeiro'
  id: '__root__' | '/' | '/cartao-de-credito' | '/controle-financeiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartaoDeCreditoRoute: typeof CartaoDeCreditoRoute
  ControleFinanceiroRoute: typeof ControleFinanceiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao-de-credito': {
      id: '/cartao-de-credito'
      path: '/cartao-de-credito'
      fullPath: '/cartao-de-credito'
      preLoaderRoute: typeof CartaoDeCreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle-financeiro': {
      id: '/controle-financeiro'
      path: '/controle-financeiro'
      fullPath: '/controle-financeiro'
      preLoaderRoute: typeof ControleFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartaoDeCreditoRoute: CartaoDeCreditoRoute,
  ControleFinanceiroRoute: ControleFinanceiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
